# Generated by Django 5.2.4 on 2025-07-27 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversation_conversation_id_message_message_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_convers_0a9604_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_message_a8c1bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_id_31c9cf_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(blank=True, db_column='participants_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
        ),
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
    ]
